[project]
name = "readinglens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-community>=0.3.18",
    "transformers>=4.49.0",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "pytest>=8.3.4",
]
